### PR TITLE
feat: print classes loaded by JVM

### PR DESCRIPTION
**Pull request by algomaster99**
For a simple Java program that takes three inputs `a`, `b`, and an arithmetic operation to perform, I have tried to print out classes in two ways: (`a` = 1, `b` = 1, arithmetic operation = `1` (add))

### Javaagent

Using the instrumentation API, I just print out whatever class is being loaded in [`classes_javaagent.txt`](https://github.com/ASSERT-KTH/terminator/compare/loading-classes?expand=1#diff-6ae9e563748e8f262a2454390e849b02225e5be99ee302337843afb860550ded). Number of classes: 146.

### JVM -Xlog

I ran the command:
```
java -Xlog:class+load=info:classes_jvm.txt -jar src/test/resources/sample-maven-project/target/i-am-affected-1.0-SNAPSHOT-jar-with-dependencies.jar
```
and we get [`classes_jvm.txt`](https://github.com/ASSERT-KTH/terminator/compare/loading-classes?expand=1#diff-077af4d3624fd392907c23d454f003da45058700b6b0bab1b667f83dc568aa6e) with much more classes loaded.

@MartinWitt, Do you think we miss some classes when we go the agent way?

### CODE REVIEW

**Comment by MartinWitt** [comment]
Could you get some kind of diff between the methods? The agent could miss classes before he is active, as the jvm init is before?

**Comment by algomaster99** [comment]
Sorry for [`03baa69` (#1)](https://github.com/ASSERT-KTH/terminator/pull/1/commits/03baa695d021d0999d7e9ae5730a675bb6d3df39) because I want to do analysis with Java 11.

One interesting thing I noticed in JVM's log is that it also tells the source jar.

**Comment by algomaster99** [comment]
> Could you get some kind of diff between the methods?

### Javagent - JVM

```
java/lang/WeakPairMap$Pair$Weak$1
java/lang/WeakPairMap$WeakRefPeer
java/lang/WeakPairMap$Pair$Weak
```

### JVM - javaagent

682 in total (alphabetically sorted so that we see the root package names)
```
java/io/BufferedInputStream
java/io/BufferedOutputStream
java/io/BufferedWriter
java/io/ByteArrayInputStream
java/io/Closeable
java/io/DataInput
java/io/DataOutput
java/io/DefaultFileSystem
java/io/ExpiringCache
java/io/ExpiringCache$1
java/io/ExpiringCache$Entry
java/io/File
java/io/File$PathStatus
java/io/FileCleanable
java/io/FileDescriptor
java/io/FileDescriptor$1
java/io/FileInputStream
java/io/FileOutputStream
java/io/FileSystem
java/io/FilterInputStream
java/io/FilterOutputStream
java/io/Flushable
java/io/InputStream
java/io/ObjectStreamField
java/io/OutputStream
java/io/OutputStreamWriter
java/io/PrintStream
java/io/RandomAccessFile
java/io/RandomAccessFile$2
java/io/Serializable
java/io/UnixFileSystem
java/io/Writer
java/lang/AbstractStringBuilder
java/lang/Appendable
java/lang/ArithmeticException
java/lang/ArrayStoreException
java/lang/AssertionStatusDirectives
java/lang/AutoCloseable
java/lang/Boolean
java/lang/BootstrapMethodError
java/lang/Byte
java/lang/Byte$ByteCache
java/lang/CharSequence
java/lang/Character
java/lang/CharacterData
java/lang/CharacterDataLatin1
java/lang/Class
java/lang/Class$1
java/lang/Class$Atomic
java/lang/Class$ReflectionData
java/lang/ClassCastException
java/lang/ClassLoader
java/lang/ClassLoader$2
java/lang/ClassLoader$NativeLibrary
java/lang/ClassLoader$ParallelLoaders
java/lang/ClassNotFoundException
java/lang/ClassValue
java/lang/ClassValue$ClassValueMap
java/lang/ClassValue$Entry
java/lang/ClassValue$Identity
java/lang/ClassValue$Version
java/lang/Cloneable
java/lang/Comparable
java/lang/Double
java/lang/Enum
java/lang/Error
java/lang/Exception
java/lang/Float
java/lang/IllegalArgumentException
java/lang/IllegalMonitorStateException
java/lang/IncompatibleClassChangeError
java/lang/Integer
java/lang/Integer$IntegerCache
java/lang/Iterable
java/lang/LinkageError
java/lang/LiveStackFrame
java/lang/LiveStackFrameInfo
java/lang/Long
java/lang/Math
java/lang/Module
java/lang/ModuleLayer
java/lang/ModuleLayer$Controller
java/lang/NamedPackage
java/lang/NoClassDefFoundError
java/lang/NoSuchFieldException
java/lang/NoSuchMethodError
java/lang/NoSuchMethodException
java/lang/NullPointerException
java/lang/Number
java/lang/Object
java/lang/OutOfMemoryError
java/lang/Package
java/lang/Package$VersionInfo
java/lang/PublicMethods$Key
java/lang/PublicMethods$MethodList
java/lang/Readable
java/lang/ReflectiveOperationException
java/lang/Runnable
java/lang/Runtime
java/lang/Runtime$Version
java/lang/RuntimeException
java/lang/RuntimePermission
java/lang/SecurityManager
java/lang/Short
java/lang/Shutdown
java/lang/Shutdown$Lock
java/lang/StackFrameInfo
java/lang/StackOverflowError
java/lang/StackStreamFactory$AbstractStackWalker
java/lang/StackTraceElement
java/lang/StackWalker
java/lang/StackWalker$StackFrame
java/lang/String
java/lang/String$CaseInsensitiveComparator
java/lang/StringBuffer
java/lang/StringBuilder
java/lang/StringCoding
java/lang/StringCoding$1
java/lang/StringCoding$Result
java/lang/StringConcatHelper
java/lang/StringLatin1
java/lang/System
java/lang/System$2
java/lang/Terminator
java/lang/Terminator$1
java/lang/Thread
java/lang/Thread$UncaughtExceptionHandler
java/lang/ThreadDeath
java/lang/ThreadGroup
java/lang/ThreadLocal
java/lang/ThreadLocal$ThreadLocalMap
java/lang/ThreadLocal$ThreadLocalMap$Entry
java/lang/Throwable
java/lang/VersionProps
java/lang/VirtualMachineError
java/lang/Void
java/lang/annotation/Annotation
java/lang/invoke/AbstractValidatingLambdaMetafactory
java/lang/invoke/BootstrapMethodInvoker
java/lang/invoke/BoundMethodHandle
java/lang/invoke/BoundMethodHandle$Specializer
java/lang/invoke/BoundMethodHandle$Specializer$Factory
java/lang/invoke/BoundMethodHandle$SpeciesData
java/lang/invoke/BoundMethodHandle$Species_L
java/lang/invoke/BoundMethodHandle$Species_LL
java/lang/invoke/BoundMethodHandle$Species_LLL
java/lang/invoke/BoundMethodHandle$Species_LLLL
java/lang/invoke/BoundMethodHandle$Species_LLLLL
java/lang/invoke/BoundMethodHandle$Species_LLLLLL
java/lang/invoke/BoundMethodHandle$Species_LLLLLLI
java/lang/invoke/BoundMethodHandle$Species_LLLLLLII
java/lang/invoke/CallSite
java/lang/invoke/ClassSpecializer
java/lang/invoke/ClassSpecializer$1
java/lang/invoke/ClassSpecializer$Factory
java/lang/invoke/ClassSpecializer$SpeciesData
java/lang/invoke/ConstantCallSite
java/lang/invoke/DelegatingMethodHandle
java/lang/invoke/DelegatingMethodHandle$Holder
java/lang/invoke/DirectMethodHandle
java/lang/invoke/DirectMethodHandle$1
java/lang/invoke/DirectMethodHandle$Accessor
java/lang/invoke/DirectMethodHandle$Holder
java/lang/invoke/InfoFromMemberName
java/lang/invoke/InnerClassLambdaMetafactory
java/lang/invoke/InnerClassLambdaMetafactory$1
java/lang/invoke/InnerClassLambdaMetafactory$ForwardingMethodGenerator
java/lang/invoke/InvokerBytecodeGenerator
java/lang/invoke/InvokerBytecodeGenerator$2
java/lang/invoke/InvokerBytecodeGenerator$CpPatch
java/lang/invoke/Invokers
java/lang/invoke/Invokers$Holder
java/lang/invoke/LambdaForm
java/lang/invoke/LambdaForm$BasicType
java/lang/invoke/LambdaForm$DMH/0x0000000800065c40
java/lang/invoke/LambdaForm$Holder
java/lang/invoke/LambdaForm$Kind
java/lang/invoke/LambdaForm$MH/0x0000000800062040
java/lang/invoke/LambdaForm$MH/0x0000000800062440
java/lang/invoke/LambdaForm$MH/0x0000000800062840
java/lang/invoke/LambdaForm$MH/0x0000000800062c40
java/lang/invoke/LambdaForm$MH/0x0000000800063440
java/lang/invoke/LambdaForm$MH/0x0000000800067440
java/lang/invoke/LambdaForm$MH/0x0000000800098040
java/lang/invoke/LambdaForm$MH/0x0000000800098440
java/lang/invoke/LambdaForm$MH/0x0000000800098840
java/lang/invoke/LambdaForm$MH/0x0000000800098c40
java/lang/invoke/LambdaForm$MH/0x0000000800099040
java/lang/invoke/LambdaForm$MH/0x0000000800099440
java/lang/invoke/LambdaForm$MH/0x0000000800099840
java/lang/invoke/LambdaForm$Name
java/lang/invoke/LambdaForm$NamedFunction
java/lang/invoke/LambdaFormBuffer
java/lang/invoke/LambdaFormEditor
java/lang/invoke/LambdaFormEditor$Transform
java/lang/invoke/LambdaMetafactory
java/lang/invoke/MemberName
java/lang/invoke/MemberName$Factory
java/lang/invoke/MethodHandle
java/lang/invoke/MethodHandleImpl
java/lang/invoke/MethodHandleImpl$1
java/lang/invoke/MethodHandleImpl$AsVarargsCollector
java/lang/invoke/MethodHandleImpl$Intrinsic
java/lang/invoke/MethodHandleImpl$IntrinsicMethodHandle
java/lang/invoke/MethodHandleInfo
java/lang/invoke/MethodHandleNatives
java/lang/invoke/MethodHandleNatives$CallSiteContext
java/lang/invoke/MethodHandleStatics
java/lang/invoke/MethodHandles
java/lang/invoke/MethodHandles$1
java/lang/invoke/MethodHandles$Lookup
java/lang/invoke/MethodType
java/lang/invoke/MethodType$ConcurrentWeakInternSet
java/lang/invoke/MethodType$ConcurrentWeakInternSet$WeakEntry
java/lang/invoke/MethodTypeForm
java/lang/invoke/MutableCallSite
java/lang/invoke/ResolvedMethodName
java/lang/invoke/SimpleMethodHandle
java/lang/invoke/StringConcatFactory
java/lang/invoke/StringConcatFactory$1
java/lang/invoke/StringConcatFactory$MethodHandleInlineCopyStrategy
java/lang/invoke/StringConcatFactory$MethodHandleInlineCopyStrategy$1
java/lang/invoke/StringConcatFactory$MethodHandleInlineCopyStrategy$2
java/lang/invoke/StringConcatFactory$MethodHandleInlineCopyStrategy$3
java/lang/invoke/StringConcatFactory$Mode
java/lang/invoke/StringConcatFactory$Recipe
java/lang/invoke/StringConcatFactory$RecipeElement
java/lang/invoke/StringConcatFactory$Strategy
java/lang/invoke/StringConcatFactory$Stringifiers
java/lang/invoke/StringConcatFactory$Stringifiers$StringifierAny
java/lang/invoke/StringConcatFactory$Stringifiers$StringifierMost
java/lang/invoke/TypeConvertingMethodAdapter
java/lang/invoke/VarForm
java/lang/invoke/VarHandle
java/lang/invoke/VarHandle$1
java/lang/invoke/VarHandle$AccessMode
java/lang/invoke/VarHandle$AccessType
java/lang/invoke/VarHandleGuards
java/lang/invoke/VarHandleInts$FieldInstanceReadOnly
java/lang/invoke/VarHandleInts$FieldInstanceReadWrite
java/lang/invoke/VarHandles
java/lang/invoke/VolatileCallSite
java/lang/module/Configuration
java/lang/module/ModuleDescriptor
java/lang/module/ModuleDescriptor$1
java/lang/module/ModuleDescriptor$Exports
java/lang/module/ModuleDescriptor$Modifier
java/lang/module/ModuleDescriptor$Opens
java/lang/module/ModuleDescriptor$Provides
java/lang/module/ModuleDescriptor$Requires
java/lang/module/ModuleDescriptor$Requires$Modifier
java/lang/module/ModuleDescriptor$Version
java/lang/module/ModuleFinder
java/lang/module/ModuleReference
java/lang/module/ResolvedModule
java/lang/ref/Cleaner
java/lang/ref/Cleaner$1
java/lang/ref/Cleaner$Cleanable
java/lang/ref/FinalReference
java/lang/ref/Finalizer
java/lang/ref/Finalizer$FinalizerThread
java/lang/ref/PhantomReference
java/lang/ref/Reference
java/lang/ref/Reference$1
java/lang/ref/Reference$ReferenceHandler
java/lang/ref/ReferenceQueue
java/lang/ref/ReferenceQueue$Lock
java/lang/ref/ReferenceQueue$Null
java/lang/ref/SoftReference
java/lang/ref/WeakReference
java/lang/reflect/AccessibleObject
java/lang/reflect/AnnotatedElement
java/lang/reflect/Array
java/lang/reflect/Constructor
java/lang/reflect/Executable
java/lang/reflect/Field
java/lang/reflect/GenericDeclaration
java/lang/reflect/Member
java/lang/reflect/Method
java/lang/reflect/Modifier
java/lang/reflect/Parameter
java/lang/reflect/ReflectAccess
java/lang/reflect/ReflectPermission
java/lang/reflect/Type
java/net/URI
java/net/URI$1
java/net/URI$Parser
java/net/URL
java/net/URL$3
java/net/URL$DefaultFactory
java/net/URLStreamHandler
java/net/URLStreamHandlerFactory
java/nio/Bits
java/nio/Bits$1
java/nio/Buffer
java/nio/Buffer$1
java/nio/ByteBuffer
java/nio/ByteOrder
java/nio/CharBuffer
java/nio/DirectByteBuffer
java/nio/DirectLongBufferU
java/nio/HeapByteBuffer
java/nio/HeapCharBuffer
java/nio/LongBuffer
java/nio/MappedByteBuffer
java/nio/charset/Charset
java/nio/charset/CharsetEncoder
java/nio/charset/CoderResult
java/nio/charset/CodingErrorAction
java/nio/charset/spi/CharsetProvider
java/nio/file/CopyOption
java/nio/file/FileSystem
java/nio/file/FileSystems
java/nio/file/FileSystems$DefaultFileSystemHolder
java/nio/file/FileSystems$DefaultFileSystemHolder$1
java/nio/file/Files
java/nio/file/LinkOption
java/nio/file/OpenOption
java/nio/file/Path
java/nio/file/StandardOpenOption
java/nio/file/Watchable
java/nio/file/attribute/AttributeView
java/nio/file/attribute/BasicFileAttributeView
java/nio/file/attribute/BasicFileAttributes
java/nio/file/attribute/DosFileAttributeView
java/nio/file/attribute/DosFileAttributes
java/nio/file/attribute/FileAttributeView
java/nio/file/attribute/FileTime
java/nio/file/attribute/PosixFileAttributes
java/nio/file/attribute/UserDefinedFileAttributeView
java/nio/file/spi/FileSystemProvider
java/security/AccessControlContext
java/security/AccessController
java/security/AllPermission
java/security/BasicPermission
java/security/BasicPermissionCollection
java/security/CodeSource
java/security/Guard
java/security/Permission
java/security/PermissionCollection
java/security/Permissions
java/security/Permissions$1
java/security/Principal
java/security/PrivilegedAction
java/security/PrivilegedExceptionAction
java/security/ProtectionDomain
java/security/ProtectionDomain$JavaSecurityAccessImpl
java/security/ProtectionDomain$Key
java/security/SecureClassLoader
java/security/SecureClassLoader$1
java/security/SecureClassLoader$CodeSourceKey
java/security/SecureClassLoader$DebugHolder
java/security/UnresolvedPermission
java/security/cert/Certificate
java/util/AbstractCollection
java/util/AbstractList
java/util/AbstractMap
java/util/AbstractMap$1
java/util/AbstractMap$1$1
java/util/AbstractSet
java/util/ArrayDeque
java/util/ArrayDeque$DeqIterator
java/util/ArrayList
java/util/ArrayList$Itr
java/util/Arrays
java/util/Arrays$ArrayItr
java/util/Arrays$ArrayList
java/util/Collection
java/util/Collections
java/util/Collections$EmptyList
java/util/Collections$EmptyMap
java/util/Collections$EmptySet
java/util/Collections$SetFromMap
java/util/Collections$SynchronizedCollection
java/util/Collections$SynchronizedSet
java/util/Collections$UnmodifiableCollection
java/util/Collections$UnmodifiableCollection$1
java/util/Collections$UnmodifiableMap
java/util/Collections$UnmodifiableSet
java/util/Comparator
java/util/Deque
java/util/Dictionary
java/util/Enumeration
java/util/HashMap
java/util/HashMap$EntryIterator
java/util/HashMap$EntrySet
java/util/HashMap$HashIterator
java/util/HashMap$KeyIterator
java/util/HashMap$KeySet
java/util/HashMap$Node
java/util/HashMap$TreeNode
java/util/HashMap$ValueIterator
java/util/HashMap$Values
java/util/HashSet
java/util/Hashtable
java/util/Hashtable$Entry
java/util/IdentityHashMap
java/util/IdentityHashMap$KeySet
java/util/ImmutableCollections
java/util/ImmutableCollections$AbstractImmutableCollection
java/util/ImmutableCollections$AbstractImmutableList
java/util/ImmutableCollections$AbstractImmutableMap
java/util/ImmutableCollections$AbstractImmutableSet
java/util/ImmutableCollections$List12
java/util/ImmutableCollections$ListItr
java/util/ImmutableCollections$ListN
java/util/ImmutableCollections$MapN
java/util/ImmutableCollections$MapN$1
java/util/ImmutableCollections$MapN$MapNIterator
java/util/ImmutableCollections$Set12
java/util/ImmutableCollections$Set12$1
java/util/ImmutableCollections$SetN
java/util/ImmutableCollections$SetN$SetNIterator
java/util/ImmutableCollections$SubList
java/util/Iterator
java/util/KeyValueHolder
java/util/LinkedHashMap
java/util/LinkedHashMap$Entry
java/util/List
java/util/ListIterator
java/util/Locale
java/util/Locale$Cache
java/util/Map
java/util/Map$Entry
java/util/Objects
java/util/Optional
java/util/Properties
java/util/Properties$EntrySet
java/util/Queue
java/util/RandomAccess
java/util/ResourceBundle$ResourceBundleProviderHelper$$Lambda$10/0x0000000800064440
java/util/Set
java/util/Vector
java/util/WeakHashMap
java/util/WeakHashMap$Entry
java/util/WeakHashMap$KeySet
java/util/concurrent/ConcurrentHashMap
java/util/concurrent/ConcurrentHashMap$BaseIterator
java/util/concurrent/ConcurrentHashMap$CollectionView
java/util/concurrent/ConcurrentHashMap$CounterCell
java/util/concurrent/ConcurrentHashMap$EntryIterator
java/util/concurrent/ConcurrentHashMap$EntrySetView
java/util/concurrent/ConcurrentHashMap$ForwardingNode
java/util/concurrent/ConcurrentHashMap$MapEntry
java/util/concurrent/ConcurrentHashMap$Node
java/util/concurrent/ConcurrentHashMap$ReservationNode
java/util/concurrent/ConcurrentHashMap$Segment
java/util/concurrent/ConcurrentHashMap$Traverser
java/util/concurrent/ConcurrentHashMap$ValueIterator
java/util/concurrent/ConcurrentHashMap$ValuesView
java/util/concurrent/ConcurrentMap
java/util/concurrent/CopyOnWriteArrayList
java/util/concurrent/ThreadFactory
java/util/concurrent/TimeUnit
java/util/concurrent/atomic/AtomicBoolean
java/util/concurrent/atomic/AtomicInteger
java/util/concurrent/atomic/AtomicLong
java/util/concurrent/locks/AbstractOwnableSynchronizer
java/util/concurrent/locks/Lock
java/util/concurrent/locks/LockSupport
java/util/concurrent/locks/ReentrantLock
java/util/function/BiFunction
java/util/function/Function
java/util/function/Supplier
java/util/jar/Attributes
java/util/jar/Attributes$Name
java/util/jar/JarEntry
java/util/jar/JarFile
java/util/jar/JarFile$1
java/util/jar/JarFile$JarFileEntry
java/util/jar/JavaUtilJarAccessImpl
java/util/jar/Manifest
java/util/jar/Manifest$FastInputStream
java/util/regex/CharPredicates$$Lambda$1/0x0000000800067040
java/util/regex/CharPredicates$$Lambda$5/0x0000000800066440
java/util/regex/Pattern$$Lambda$13/0x0000000800063040
java/util/regex/Pattern$$Lambda$2/0x0000000800066840
java/util/regex/Pattern$$Lambda$4/0x0000000800066040
java/util/regex/Pattern$$Lambda$6/0x0000000800065840
java/util/regex/Pattern$BitClass$$Lambda$3/0x0000000800066c40
java/util/regex/Pattern$CharPredicate$$Lambda$12/0x0000000800063c40
java/util/regex/Pattern$CharPredicate$$Lambda$7/0x0000000800065040
java/util/regex/Pattern$CharPredicate$$Lambda$8/0x0000000800065440
java/util/zip/Inflater
java/util/zip/Inflater$InflaterZStreamRef
java/util/zip/InflaterInputStream
java/util/zip/ZipCoder
java/util/zip/ZipCoder$UTF8
java/util/zip/ZipConstants
java/util/zip/ZipEntry
java/util/zip/ZipFile
java/util/zip/ZipFile$1
java/util/zip/ZipFile$CleanableResource
java/util/zip/ZipFile$InflaterCleanupAction
java/util/zip/ZipFile$Source
java/util/zip/ZipFile$Source$End
java/util/zip/ZipFile$Source$Key
java/util/zip/ZipFile$ZipFileInflaterInputStream
java/util/zip/ZipFile$ZipFileInputStream
java/util/zip/ZipUtils
jdk/internal/loader/AbstractClassLoaderValue
jdk/internal/loader/BootLoader
jdk/internal/loader/BuiltinClassLoader
jdk/internal/loader/BuiltinClassLoader$LoadedModule
jdk/internal/loader/ClassLoaderValue
jdk/internal/loader/ClassLoaders
jdk/internal/loader/ClassLoaders$AppClassLoader
jdk/internal/loader/ClassLoaders$BootClassLoader
jdk/internal/loader/ClassLoaders$PlatformClassLoader
jdk/internal/loader/FileURLMapper
jdk/internal/loader/Resource
jdk/internal/loader/URLClassPath
jdk/internal/loader/URLClassPath$3
jdk/internal/loader/URLClassPath$JarLoader
jdk/internal/loader/URLClassPath$JarLoader$1
jdk/internal/loader/URLClassPath$JarLoader$2
jdk/internal/loader/URLClassPath$Loader
jdk/internal/misc/InnocuousThread
jdk/internal/misc/InnocuousThread$2
jdk/internal/misc/InnocuousThread$3
jdk/internal/misc/JavaIOFileDescriptorAccess
jdk/internal/misc/JavaIORandomAccessFileAccess
jdk/internal/misc/JavaLangAccess
jdk/internal/misc/JavaLangInvokeAccess
jdk/internal/misc/JavaLangModuleAccess
jdk/internal/misc/JavaLangRefAccess
jdk/internal/misc/JavaNetURLAccess
jdk/internal/misc/JavaNetUriAccess
jdk/internal/misc/JavaNioAccess
jdk/internal/misc/JavaNioAccess$BufferPool
jdk/internal/misc/JavaSecurityAccess
jdk/internal/misc/JavaUtilJarAccess
jdk/internal/misc/JavaUtilZipFileAccess
jdk/internal/misc/OSEnvironment
jdk/internal/misc/SharedSecrets
jdk/internal/misc/Signal
jdk/internal/misc/Signal$Handler
jdk/internal/misc/Signal$NativeHandler
jdk/internal/misc/TerminatingThreadLocal
jdk/internal/misc/TerminatingThreadLocal$1
jdk/internal/misc/Unsafe
jdk/internal/misc/VM
jdk/internal/module/ArchivedModuleGraph
jdk/internal/module/Builder
jdk/internal/module/IllegalAccessLogger
jdk/internal/module/IllegalAccessLogger$Builder
jdk/internal/module/IllegalAccessLogger$Mode
jdk/internal/module/ModuleBootstrap
jdk/internal/module/ModuleBootstrap$2
jdk/internal/module/ModuleBootstrap$Counters
jdk/internal/module/ModuleHashes
jdk/internal/module/ModuleHashes$Builder
jdk/internal/module/ModuleHashes$HashSupplier
jdk/internal/module/ModuleLoaderMap
jdk/internal/module/ModuleLoaderMap$Mapper
jdk/internal/module/ModulePatcher
jdk/internal/module/ModuleReferenceImpl
jdk/internal/module/ModuleResolution
jdk/internal/module/ModuleTarget
jdk/internal/module/Modules
jdk/internal/module/ServicesCatalog
jdk/internal/module/ServicesCatalog$ServiceProvider
jdk/internal/module/SystemModuleFinders
jdk/internal/module/SystemModuleFinders$2
jdk/internal/module/SystemModuleFinders$3
jdk/internal/module/SystemModuleFinders$SystemModuleFinder
jdk/internal/module/SystemModules
jdk/internal/module/SystemModules$default
jdk/internal/module/SystemModulesMap
jdk/internal/org/objectweb/asm/AnnotationVisitor
jdk/internal/org/objectweb/asm/AnnotationWriter
jdk/internal/org/objectweb/asm/ByteVector
jdk/internal/org/objectweb/asm/ClassVisitor
jdk/internal/org/objectweb/asm/ClassWriter
jdk/internal/org/objectweb/asm/FieldVisitor
jdk/internal/org/objectweb/asm/FieldWriter
jdk/internal/org/objectweb/asm/Frame
jdk/internal/org/objectweb/asm/Item
jdk/internal/org/objectweb/asm/Label
jdk/internal/org/objectweb/asm/MethodVisitor
jdk/internal/org/objectweb/asm/MethodWriter
jdk/internal/org/objectweb/asm/Type
jdk/internal/perf/Perf
jdk/internal/perf/Perf$GetPerfAction
jdk/internal/perf/PerfCounter
jdk/internal/perf/PerfCounter$CoreCounters
jdk/internal/ref/Cleaner
jdk/internal/ref/CleanerFactory
jdk/internal/ref/CleanerFactory$1
jdk/internal/ref/CleanerFactory$1$1
jdk/internal/ref/CleanerImpl
jdk/internal/ref/CleanerImpl$CleanerCleanable
jdk/internal/ref/CleanerImpl$PhantomCleanableRef
jdk/internal/ref/CleanerImpl$SoftCleanableRef
jdk/internal/ref/CleanerImpl$WeakCleanableRef
jdk/internal/ref/PhantomCleanable
jdk/internal/ref/SoftCleanable
jdk/internal/ref/WeakCleanable
jdk/internal/reflect/CallerSensitive
jdk/internal/reflect/ConstantPool
jdk/internal/reflect/ConstructorAccessor
jdk/internal/reflect/ConstructorAccessorImpl
jdk/internal/reflect/DelegatingClassLoader
jdk/internal/reflect/DelegatingConstructorAccessorImpl
jdk/internal/reflect/FieldAccessor
jdk/internal/reflect/FieldAccessorImpl
jdk/internal/reflect/LangReflectAccess
jdk/internal/reflect/MagicAccessorImpl
jdk/internal/reflect/MethodAccessor
jdk/internal/reflect/MethodAccessorImpl
jdk/internal/reflect/NativeConstructorAccessorImpl
jdk/internal/reflect/Reflection
jdk/internal/reflect/ReflectionFactory
jdk/internal/reflect/ReflectionFactory$GetReflectionFactoryAction
jdk/internal/reflect/UnsafeFieldAccessorImpl
jdk/internal/reflect/UnsafeStaticFieldAccessorImpl
jdk/internal/util/Preconditions
jdk/internal/util/Preconditions$1
jdk/internal/util/StaticProperty
jdk/internal/util/jar/JarIndex
sun/invoke/empty/Empty
sun/invoke/util/BytecodeDescriptor
sun/invoke/util/ValueConversions
sun/invoke/util/ValueConversions$WrapperCache
sun/invoke/util/VerifyAccess
sun/invoke/util/VerifyType
sun/invoke/util/Wrapper
sun/invoke/util/Wrapper$1
sun/invoke/util/Wrapper$Format
sun/net/util/IPAddressUtil
sun/net/util/URLUtil
sun/net/www/ParseUtil
sun/net/www/protocol/file/Handler
sun/net/www/protocol/jar/Handler
sun/net/www/protocol/jrt/Handler
sun/nio/ByteBuffered
sun/nio/ch/DirectBuffer
sun/nio/cs/HistoricallyNamedCharset
sun/nio/cs/ISO_8859_1
sun/nio/cs/StandardCharsets
sun/nio/cs/StreamEncoder
sun/nio/cs/US_ASCII
sun/nio/cs/UTF_8
sun/nio/cs/UTF_8$Encoder
sun/nio/cs/Unicode
sun/nio/fs/AbstractBasicFileAttributeView
sun/nio/fs/AbstractFileSystemProvider
sun/nio/fs/DefaultFileSystemProvider
sun/nio/fs/DynamicFileAttributeView
sun/nio/fs/LinuxFileSystem
sun/nio/fs/LinuxFileSystemProvider
sun/nio/fs/NativeBuffer
sun/nio/fs/NativeBuffer$Deallocator
sun/nio/fs/NativeBuffers
sun/nio/fs/NativeBuffers$1
sun/nio/fs/UnixFileAttributeViews
sun/nio/fs/UnixFileAttributeViews$Basic
sun/nio/fs/UnixFileAttributes
sun/nio/fs/UnixFileAttributes$UnixAsBasicFileAttributes
sun/nio/fs/UnixFileStoreAttributes
sun/nio/fs/UnixFileSystem
sun/nio/fs/UnixFileSystemProvider
sun/nio/fs/UnixMountEntry
sun/nio/fs/UnixNativeDispatcher
sun/nio/fs/UnixNativeDispatcher$1
sun/nio/fs/UnixPath
sun/nio/fs/Util
sun/reflect/misc/ReflectUtil
sun/security/action/GetBooleanAction
sun/security/action/GetPropertyAction
sun/security/util/Debug
sun/security/util/LazyCodeSourcePermissionCollection
sun/util/locale/BaseLocale
sun/util/locale/BaseLocale$Cache
sun/util/locale/BaseLocale$Key
sun/util/locale/InternalLocaleBuilder
sun/util/locale/InternalLocaleBuilder$CaseInsensitiveChar
sun/util/locale/LocaleObjectCache
sun/util/locale/LocaleObjectCache$CacheEntry
sun/util/locale/LocaleUtils
sun/util/locale/provider/JRELocaleProviderAdapter$$Lambda$11/0x0000000800063840
sun/util/locale/provider/JRELocaleProviderAdapter$$Lambda$9/0x0000000800064040
```

**Comment by algomaster99** [comment]
@MartinWitt can we comment on some fixed classes that will always be loaded for JVM init irrespective of JVM runs a jar or a classfile?

**Comment by algomaster99** [comment]
I am noting differences [here](https://colab.research.google.com/drive/11FtR0tuC7bC91R0-HPtL5NaJW5rECMYe?usp=sharing).

**Comment by algomaster99** [comment]
We have a list of classes that we get post-initialisation of JVM[1], but they haven't been loaded. Let's try to map their source now. We may need to add an external library to test it.

[1]: The classes used for initialising the JVM are mainly from these packages - `java.net`,`sun.nio`,`sun.util`,`java.lang`,`java.nio`,`java.util`,`jdk.internal`,`sun.invoke`,`java.io`,`sun.security`,`java.security`,`sun.net`. We can ignore them as these are fully controlled by JVM.

**Pull request merged**
